#!/usr/bin/env bash
# Full document build. Run from the project directory: bash build.sh
#
# Order matters: the appendices are derived FROM the body, so the body has to be
# assembled first, without an appendix present. Running the steps out of order
# would feed the appendix back into itself.
set -euo pipefail

export PYTHONIOENCODING=utf-8

# Choose a working Python. `python3` exists on macOS and Linux; on Windows it is
# usually a Microsoft Store stub that prints an advert and exits 0, so it is
# tested by running it rather than by looking for it on PATH.
if python3 -c "import sys" >/dev/null 2>&1; then
  PY=python3
elif python -c "import sys" >/dev/null 2>&1; then
  PY=python
else
  echo "No working Python found. Install Python 3 and re-run." >&2
  exit 1
fi
echo "using $PY ($($PY --version 2>&1))"

echo "== 1/8  assemble body (no appendix) =="
rm -f parts/appendix.md
"$PY" assemble.py parts SPEC_body.md

echo
echo "== 2/8  derive appendices from the body =="
"$PY" make_appendix.py SPEC_body.md parts brother_doc_dump.txt parts/appendix.md

echo
echo "== 3/8  assemble the full document =="
"$PY" assemble.py parts SPEC.md

echo
echo "== 4/8  build the laboratory overview (a subset of the full document) =="
"$PY" make_brief.py parts BRIEF.md

echo
echo "== 5/8  refresh review digests =="
"$PY" make_digest.py SPEC.md digests

echo
echo "== 6/8  render Word documents =="
node build_doc.js SPEC.md "Silk Testing Laboratory System - Full Specification.docx"
node build_doc.js BRIEF.md "Silk Testing Laboratory System - Overview for the Lab.docx" brief_meta.json

echo
echo "== 7/8  render the visual guide =="
# Content comes from guide_content.json. That file is distilled from the spec by
# hand or by agents, not generated by a script here, so edit it directly to
# change the guide's wording.
node build_guide.js guide_content.json index.html guide_meta.json

echo
echo "== 8/8  render the Phase 0 field kit =="
# Content lives in fieldkit_content.json; edit that to change the wording.
node build_fieldkit.js fieldkit_content.json "Phase 0 Field Kit.html"

echo
echo "done."
