#!/usr/bin/env bash
# Full document build. Run from the project directory: bash build.sh
#
# Order matters: the appendices are derived FROM the body, so the body has to be
# assembled first, without an appendix present. Running the steps out of order
# would feed the appendix back into itself.
set -euo pipefail

export PYTHONIOENCODING=utf-8

echo "== 1/7  assemble body (no appendix) =="
rm -f parts/appendix.md
python assemble.py parts SPEC_body.md

echo
echo "== 2/7  derive appendices from the body =="
python make_appendix.py SPEC_body.md parts brother_doc_dump.txt parts/appendix.md

echo
echo "== 3/7  assemble the full document =="
python assemble.py parts SPEC.md

echo
echo "== 4/7  build the laboratory overview (a subset of the full document) =="
python make_brief.py parts BRIEF.md

echo
echo "== 5/7  refresh review digests =="
python make_digest.py SPEC.md digests

echo
echo "== 6/7  render Word documents =="
node build_doc.js SPEC.md "Silk Testing Laboratory System - Full Specification.docx"
node build_doc.js BRIEF.md "Silk Testing Laboratory System - Overview for the Lab.docx" brief_meta.json

echo
echo "== 7/7  render the visual guide =="
# Content comes from guide_content.json. That file is distilled from the spec by
# hand or by agents, not generated by a script here, so edit it directly to
# change the guide's wording.
node build_guide.js guide_content.json "Silk Lab System - Visual Guide.html" guide_meta.json

echo
echo "done."
